### ISSUE TITLE
Parameter handler must be specified

### ISSUE THREAD

**Issue by qsys** [knalli/angular-vertxbus#48]
I wrapped the provider inside a service (to add some app-specific logging etc). All works fine, except unregistering handlers:

    Error: Parameter handler must be specified
       at checkSpecified (http://<host>/angular.dev/js/vertxbus.js:193:9)
       at unregisterHandler (http://<host>/angular.dev/js/vertxbus.js:83:7)
       at unregisterHandler (http://<host>/angular.dev/lib/angular/angular-vertxbus.js:204:13)
       at unregisterHandler (http://<host>/angular.dev/lib/angular/angular-vertxbus.js:521:11)
       at unregisterHandler (http://<host>/angular.dev/lib/angular/angular-vertxbus.js:628:13)
       at Anonymous function (http://<host>/angular.dev/modules/index/js/services.js:169:17)
       at dofunc (http://<host>/angular.dev/modules/index/js/services.js:129:17)
       at un (http://<host>/angular.dev/modules/index/js/services.js:167:13)

While debugging, I found out that there is a callback, but deconstructors is empty at line 520: `{"keys":[null],"values":[null]}`

Digging a little further, registering the handler doesn't seem to work out fine: at line 511: `{"keys":[null],"values":[null]}`, so deconstructors.get(callback) returns `'undefined'`. I do, however, have a callback- and deconstructor-function.

In my code: `'services.js'`, line 169:

    vertxEventBusService.un(<address>, function (msg) {
        [...]
    });

Function `'dofunc'` doesn't do really much, except some logging and a few small checks, afterwards, it just executes the callback. From line 167:

            dofunc(args, function (args) {
                logger.debug([...]);
                vertxEventBusService.un(args.address, function (msg) {
                    logger.debug([...]);
                    args.handler(msg);
                });
            });

**Comment by knalli** [comment]
I do not get it. Which files, which lines, which code? Which version are you using? It does not look like 1.0.0...

**Comment by knalli** [comment]
Dup for #52
